/*
 * This file is generated by jOOQ.
 */
package ru.itis.ibragimovaidar.jooqgenerator.jooq.support;


import ru.imark.itobacco.test.integration.jooq.support.tables.PgStatStatements;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupportTables {

    /**
     * The table <code>public.pg_stat_statements</code>.
     */
    public static final PgStatStatements PG_STAT_STATEMENTS = PgStatStatements.PG_STAT_STATEMENTS;
}
