/*
 * This file is generated by jOOQ.
 */
package ru.itis.ibragimovaidar.jooqgenerator.jooq.support;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import ru.imark.itobacco.test.integration.jooq.support.tables.PgStatStatements;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupportSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final SupportSchema PUBLIC = new SupportSchema();

    /**
     * The table <code>public.pg_stat_statements</code>.
     */
    public final PgStatStatements PG_STAT_STATEMENTS = PgStatStatements.PG_STAT_STATEMENTS;

    /**
     * No further instances allowed
     */
    private SupportSchema() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            PgStatStatements.PG_STAT_STATEMENTS);
    }
}
