/*
 * This file is generated by jOOQ.
 */
package ru.itis.ibragimovaidar.jooqgenerator.jooq.support;


import org.jooq.Configuration;
import ru.imark.itobacco.test.integration.jooq.support.routines.PgStatStatementsReset;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupportRoutines {

    /**
     * Call <code>public.pg_stat_statements_reset</code>
     */
    public static void pgStatStatementsReset(
          Configuration configuration
        , Long userid
        , Long dbid
        , Long queryid
    ) {
        PgStatStatementsReset p = new PgStatStatementsReset();
        p.setUserid(userid);
        p.setDbid(dbid);
        p.setQueryid(queryid);

        p.execute(configuration);
    }
}
