/*
 * This file is generated by jOOQ.
 */
package ru.itis.ibragimovaidar.jooqgenerator.jooq.support.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import ru.imark.itobacco.test.integration.jooq.support.SupportSchema;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatStatementsReset extends AbstractRoutine<Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.pg_stat_statements_reset.userid</code>.
     */
    public static final Parameter<Long> USERID = Internal.createParameter("userid", SQLDataType.BIGINT.defaultValue(DSL.field("0", SQLDataType.BIGINT)), true, false);

    /**
     * The parameter <code>public.pg_stat_statements_reset.dbid</code>.
     */
    public static final Parameter<Long> DBID = Internal.createParameter("dbid", SQLDataType.BIGINT.defaultValue(DSL.field("0", SQLDataType.BIGINT)), true, false);

    /**
     * The parameter <code>public.pg_stat_statements_reset.queryid</code>.
     */
    public static final Parameter<Long> QUERYID = Internal.createParameter("queryid", SQLDataType.BIGINT.defaultValue(DSL.field("0", SQLDataType.BIGINT)), true, false);

    /**
     * Create a new routine call instance
     */
    public PgStatStatementsReset() {
        super("pg_stat_statements_reset", SupportSchema.PUBLIC);

        addInParameter(USERID);
        addInParameter(DBID);
        addInParameter(QUERYID);
    }

    /**
     * Set the <code>userid</code> parameter IN value to the routine
     */
    public void setUserid(Long value) {
        setValue(USERID, value);
    }

    /**
     * Set the <code>dbid</code> parameter IN value to the routine
     */
    public void setDbid(Long value) {
        setValue(DBID, value);
    }

    /**
     * Set the <code>queryid</code> parameter IN value to the routine
     */
    public void setQueryid(Long value) {
        setValue(QUERYID, value);
    }
}
