/*
 * This file is generated by jOOQ.
 */
package ru.itis.ibragimovaidar.jooqgenerator.jooq.support.tables.records;


import org.jooq.impl.TableRecordImpl;
import ru.imark.itobacco.test.integration.jooq.support.tables.PgStatStatements;

import javax.annotation.processing.Generated;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatStatementsRecord extends TableRecordImpl<PgStatStatementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.pg_stat_statements.userid</code>.
     */
    public PgStatStatementsRecord setUserid(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pg_stat_statements.dbid</code>.
     */
    public PgStatStatementsRecord setDbid(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.dbid</code>.
     */
    public Long getDbid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.pg_stat_statements.queryid</code>.
     */
    public PgStatStatementsRecord setQueryid(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.queryid</code>.
     */
    public Long getQueryid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.pg_stat_statements.query</code>.
     */
    public PgStatStatementsRecord setQuery(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.query</code>.
     */
    public String getQuery() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.pg_stat_statements.plans</code>.
     */
    public PgStatStatementsRecord setPlans(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.plans</code>.
     */
    public Long getPlans() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.pg_stat_statements.total_plan_time</code>.
     */
    public PgStatStatementsRecord setTotalPlanTime(Double value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.total_plan_time</code>.
     */
    public Double getTotalPlanTime() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.pg_stat_statements.min_plan_time</code>.
     */
    public PgStatStatementsRecord setMinPlanTime(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.min_plan_time</code>.
     */
    public Double getMinPlanTime() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.pg_stat_statements.max_plan_time</code>.
     */
    public PgStatStatementsRecord setMaxPlanTime(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.max_plan_time</code>.
     */
    public Double getMaxPlanTime() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.pg_stat_statements.mean_plan_time</code>.
     */
    public PgStatStatementsRecord setMeanPlanTime(Double value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.mean_plan_time</code>.
     */
    public Double getMeanPlanTime() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>public.pg_stat_statements.stddev_plan_time</code>.
     */
    public PgStatStatementsRecord setStddevPlanTime(Double value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.stddev_plan_time</code>.
     */
    public Double getStddevPlanTime() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.pg_stat_statements.calls</code>.
     */
    public PgStatStatementsRecord setCalls(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.calls</code>.
     */
    public Long getCalls() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.pg_stat_statements.total_exec_time</code>.
     */
    public PgStatStatementsRecord setTotalExecTime(Double value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.total_exec_time</code>.
     */
    public Double getTotalExecTime() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>public.pg_stat_statements.min_exec_time</code>.
     */
    public PgStatStatementsRecord setMinExecTime(Double value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.min_exec_time</code>.
     */
    public Double getMinExecTime() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.pg_stat_statements.max_exec_time</code>.
     */
    public PgStatStatementsRecord setMaxExecTime(Double value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.max_exec_time</code>.
     */
    public Double getMaxExecTime() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>public.pg_stat_statements.mean_exec_time</code>.
     */
    public PgStatStatementsRecord setMeanExecTime(Double value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.mean_exec_time</code>.
     */
    public Double getMeanExecTime() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>public.pg_stat_statements.stddev_exec_time</code>.
     */
    public PgStatStatementsRecord setStddevExecTime(Double value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.stddev_exec_time</code>.
     */
    public Double getStddevExecTime() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>public.pg_stat_statements.rows</code>.
     */
    public PgStatStatementsRecord setRows(Long value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.rows</code>.
     */
    public Long getRows() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_hit</code>.
     */
    public PgStatStatementsRecord setSharedBlksHit(Long value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_hit</code>.
     */
    public Long getSharedBlksHit() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_read</code>.
     */
    public PgStatStatementsRecord setSharedBlksRead(Long value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_read</code>.
     */
    public Long getSharedBlksRead() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_dirtied</code>.
     */
    public PgStatStatementsRecord setSharedBlksDirtied(Long value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_dirtied</code>.
     */
    public Long getSharedBlksDirtied() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_written</code>.
     */
    public PgStatStatementsRecord setSharedBlksWritten(Long value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_written</code>.
     */
    public Long getSharedBlksWritten() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_hit</code>.
     */
    public PgStatStatementsRecord setLocalBlksHit(Long value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_hit</code>.
     */
    public Long getLocalBlksHit() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_read</code>.
     */
    public PgStatStatementsRecord setLocalBlksRead(Long value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_read</code>.
     */
    public Long getLocalBlksRead() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_dirtied</code>.
     */
    public PgStatStatementsRecord setLocalBlksDirtied(Long value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_dirtied</code>.
     */
    public Long getLocalBlksDirtied() {
        return (Long) get(23);
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_written</code>.
     */
    public PgStatStatementsRecord setLocalBlksWritten(Long value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_written</code>.
     */
    public Long getLocalBlksWritten() {
        return (Long) get(24);
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blks_read</code>.
     */
    public PgStatStatementsRecord setTempBlksRead(Long value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blks_read</code>.
     */
    public Long getTempBlksRead() {
        return (Long) get(25);
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blks_written</code>.
     */
    public PgStatStatementsRecord setTempBlksWritten(Long value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blks_written</code>.
     */
    public Long getTempBlksWritten() {
        return (Long) get(26);
    }

    /**
     * Setter for <code>public.pg_stat_statements.blk_read_time</code>.
     */
    public PgStatStatementsRecord setBlkReadTime(Double value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.blk_read_time</code>.
     */
    public Double getBlkReadTime() {
        return (Double) get(27);
    }

    /**
     * Setter for <code>public.pg_stat_statements.blk_write_time</code>.
     */
    public PgStatStatementsRecord setBlkWriteTime(Double value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.blk_write_time</code>.
     */
    public Double getBlkWriteTime() {
        return (Double) get(28);
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_records</code>.
     */
    public PgStatStatementsRecord setWalRecords(Long value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_records</code>.
     */
    public Long getWalRecords() {
        return (Long) get(29);
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_fpi</code>.
     */
    public PgStatStatementsRecord setWalFpi(Long value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_fpi</code>.
     */
    public Long getWalFpi() {
        return (Long) get(30);
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_bytes</code>.
     */
    public PgStatStatementsRecord setWalBytes(BigDecimal value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_bytes</code>.
     */
    public BigDecimal getWalBytes() {
        return (BigDecimal) get(31);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PgStatStatementsRecord
     */
    public PgStatStatementsRecord() {
        super(PgStatStatements.PG_STAT_STATEMENTS);
    }

    /**
     * Create a detached, initialised PgStatStatementsRecord
     */
    public PgStatStatementsRecord(Long userid, Long dbid, Long queryid, String query, Long plans, Double totalPlanTime, Double minPlanTime, Double maxPlanTime, Double meanPlanTime, Double stddevPlanTime, Long calls, Double totalExecTime, Double minExecTime, Double maxExecTime, Double meanExecTime, Double stddevExecTime, Long rows, Long sharedBlksHit, Long sharedBlksRead, Long sharedBlksDirtied, Long sharedBlksWritten, Long localBlksHit, Long localBlksRead, Long localBlksDirtied, Long localBlksWritten, Long tempBlksRead, Long tempBlksWritten, Double blkReadTime, Double blkWriteTime, Long walRecords, Long walFpi, BigDecimal walBytes) {
        super(PgStatStatements.PG_STAT_STATEMENTS);

        setUserid(userid);
        setDbid(dbid);
        setQueryid(queryid);
        setQuery(query);
        setPlans(plans);
        setTotalPlanTime(totalPlanTime);
        setMinPlanTime(minPlanTime);
        setMaxPlanTime(maxPlanTime);
        setMeanPlanTime(meanPlanTime);
        setStddevPlanTime(stddevPlanTime);
        setCalls(calls);
        setTotalExecTime(totalExecTime);
        setMinExecTime(minExecTime);
        setMaxExecTime(maxExecTime);
        setMeanExecTime(meanExecTime);
        setStddevExecTime(stddevExecTime);
        setRows(rows);
        setSharedBlksHit(sharedBlksHit);
        setSharedBlksRead(sharedBlksRead);
        setSharedBlksDirtied(sharedBlksDirtied);
        setSharedBlksWritten(sharedBlksWritten);
        setLocalBlksHit(localBlksHit);
        setLocalBlksRead(localBlksRead);
        setLocalBlksDirtied(localBlksDirtied);
        setLocalBlksWritten(localBlksWritten);
        setTempBlksRead(tempBlksRead);
        setTempBlksWritten(tempBlksWritten);
        setBlkReadTime(blkReadTime);
        setBlkWriteTime(blkWriteTime);
        setWalRecords(walRecords);
        setWalFpi(walFpi);
        setWalBytes(walBytes);
    }
}
