/*
 * This file is generated by jOOQ.
 */
package ru.itis.ibragimovaidar.jooqgenerator.jooq.support.tables.pojos;


import javax.annotation.processing.Generated;
import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PgStatStatementsPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long       userid;
    private Long       dbid;
    private Long       queryid;
    private String     query;
    private Long       plans;
    private Double     totalPlanTime;
    private Double     minPlanTime;
    private Double     maxPlanTime;
    private Double     meanPlanTime;
    private Double     stddevPlanTime;
    private Long       calls;
    private Double     totalExecTime;
    private Double     minExecTime;
    private Double     maxExecTime;
    private Double     meanExecTime;
    private Double     stddevExecTime;
    private Long       rows;
    private Long       sharedBlksHit;
    private Long       sharedBlksRead;
    private Long       sharedBlksDirtied;
    private Long       sharedBlksWritten;
    private Long       localBlksHit;
    private Long       localBlksRead;
    private Long       localBlksDirtied;
    private Long       localBlksWritten;
    private Long       tempBlksRead;
    private Long       tempBlksWritten;
    private Double     blkReadTime;
    private Double     blkWriteTime;
    private Long       walRecords;
    private Long       walFpi;
    private BigDecimal walBytes;

    public PgStatStatementsPojo() {}

    public PgStatStatementsPojo(PgStatStatementsPojo value) {
        this.userid = value.userid;
        this.dbid = value.dbid;
        this.queryid = value.queryid;
        this.query = value.query;
        this.plans = value.plans;
        this.totalPlanTime = value.totalPlanTime;
        this.minPlanTime = value.minPlanTime;
        this.maxPlanTime = value.maxPlanTime;
        this.meanPlanTime = value.meanPlanTime;
        this.stddevPlanTime = value.stddevPlanTime;
        this.calls = value.calls;
        this.totalExecTime = value.totalExecTime;
        this.minExecTime = value.minExecTime;
        this.maxExecTime = value.maxExecTime;
        this.meanExecTime = value.meanExecTime;
        this.stddevExecTime = value.stddevExecTime;
        this.rows = value.rows;
        this.sharedBlksHit = value.sharedBlksHit;
        this.sharedBlksRead = value.sharedBlksRead;
        this.sharedBlksDirtied = value.sharedBlksDirtied;
        this.sharedBlksWritten = value.sharedBlksWritten;
        this.localBlksHit = value.localBlksHit;
        this.localBlksRead = value.localBlksRead;
        this.localBlksDirtied = value.localBlksDirtied;
        this.localBlksWritten = value.localBlksWritten;
        this.tempBlksRead = value.tempBlksRead;
        this.tempBlksWritten = value.tempBlksWritten;
        this.blkReadTime = value.blkReadTime;
        this.blkWriteTime = value.blkWriteTime;
        this.walRecords = value.walRecords;
        this.walFpi = value.walFpi;
        this.walBytes = value.walBytes;
    }

    public PgStatStatementsPojo(
        Long       userid,
        Long       dbid,
        Long       queryid,
        String     query,
        Long       plans,
        Double     totalPlanTime,
        Double     minPlanTime,
        Double     maxPlanTime,
        Double     meanPlanTime,
        Double     stddevPlanTime,
        Long       calls,
        Double     totalExecTime,
        Double     minExecTime,
        Double     maxExecTime,
        Double     meanExecTime,
        Double     stddevExecTime,
        Long       rows,
        Long       sharedBlksHit,
        Long       sharedBlksRead,
        Long       sharedBlksDirtied,
        Long       sharedBlksWritten,
        Long       localBlksHit,
        Long       localBlksRead,
        Long       localBlksDirtied,
        Long       localBlksWritten,
        Long       tempBlksRead,
        Long       tempBlksWritten,
        Double     blkReadTime,
        Double     blkWriteTime,
        Long       walRecords,
        Long       walFpi,
        BigDecimal walBytes
    ) {
        this.userid = userid;
        this.dbid = dbid;
        this.queryid = queryid;
        this.query = query;
        this.plans = plans;
        this.totalPlanTime = totalPlanTime;
        this.minPlanTime = minPlanTime;
        this.maxPlanTime = maxPlanTime;
        this.meanPlanTime = meanPlanTime;
        this.stddevPlanTime = stddevPlanTime;
        this.calls = calls;
        this.totalExecTime = totalExecTime;
        this.minExecTime = minExecTime;
        this.maxExecTime = maxExecTime;
        this.meanExecTime = meanExecTime;
        this.stddevExecTime = stddevExecTime;
        this.rows = rows;
        this.sharedBlksHit = sharedBlksHit;
        this.sharedBlksRead = sharedBlksRead;
        this.sharedBlksDirtied = sharedBlksDirtied;
        this.sharedBlksWritten = sharedBlksWritten;
        this.localBlksHit = localBlksHit;
        this.localBlksRead = localBlksRead;
        this.localBlksDirtied = localBlksDirtied;
        this.localBlksWritten = localBlksWritten;
        this.tempBlksRead = tempBlksRead;
        this.tempBlksWritten = tempBlksWritten;
        this.blkReadTime = blkReadTime;
        this.blkWriteTime = blkWriteTime;
        this.walRecords = walRecords;
        this.walFpi = walFpi;
        this.walBytes = walBytes;
    }

    /**
     * Getter for <code>public.pg_stat_statements.userid</code>.
     */
    public Long getUserid() {
        return this.userid;
    }

    /**
     * Setter for <code>public.pg_stat_statements.userid</code>.
     */
    public PgStatStatementsPojo setUserid(Long userid) {
        this.userid = userid;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.dbid</code>.
     */
    public Long getDbid() {
        return this.dbid;
    }

    /**
     * Setter for <code>public.pg_stat_statements.dbid</code>.
     */
    public PgStatStatementsPojo setDbid(Long dbid) {
        this.dbid = dbid;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.queryid</code>.
     */
    public Long getQueryid() {
        return this.queryid;
    }

    /**
     * Setter for <code>public.pg_stat_statements.queryid</code>.
     */
    public PgStatStatementsPojo setQueryid(Long queryid) {
        this.queryid = queryid;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.query</code>.
     */
    public String getQuery() {
        return this.query;
    }

    /**
     * Setter for <code>public.pg_stat_statements.query</code>.
     */
    public PgStatStatementsPojo setQuery(String query) {
        this.query = query;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.plans</code>.
     */
    public Long getPlans() {
        return this.plans;
    }

    /**
     * Setter for <code>public.pg_stat_statements.plans</code>.
     */
    public PgStatStatementsPojo setPlans(Long plans) {
        this.plans = plans;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.total_plan_time</code>.
     */
    public Double getTotalPlanTime() {
        return this.totalPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.total_plan_time</code>.
     */
    public PgStatStatementsPojo setTotalPlanTime(Double totalPlanTime) {
        this.totalPlanTime = totalPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.min_plan_time</code>.
     */
    public Double getMinPlanTime() {
        return this.minPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.min_plan_time</code>.
     */
    public PgStatStatementsPojo setMinPlanTime(Double minPlanTime) {
        this.minPlanTime = minPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.max_plan_time</code>.
     */
    public Double getMaxPlanTime() {
        return this.maxPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.max_plan_time</code>.
     */
    public PgStatStatementsPojo setMaxPlanTime(Double maxPlanTime) {
        this.maxPlanTime = maxPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.mean_plan_time</code>.
     */
    public Double getMeanPlanTime() {
        return this.meanPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.mean_plan_time</code>.
     */
    public PgStatStatementsPojo setMeanPlanTime(Double meanPlanTime) {
        this.meanPlanTime = meanPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.stddev_plan_time</code>.
     */
    public Double getStddevPlanTime() {
        return this.stddevPlanTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.stddev_plan_time</code>.
     */
    public PgStatStatementsPojo setStddevPlanTime(Double stddevPlanTime) {
        this.stddevPlanTime = stddevPlanTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.calls</code>.
     */
    public Long getCalls() {
        return this.calls;
    }

    /**
     * Setter for <code>public.pg_stat_statements.calls</code>.
     */
    public PgStatStatementsPojo setCalls(Long calls) {
        this.calls = calls;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.total_exec_time</code>.
     */
    public Double getTotalExecTime() {
        return this.totalExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.total_exec_time</code>.
     */
    public PgStatStatementsPojo setTotalExecTime(Double totalExecTime) {
        this.totalExecTime = totalExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.min_exec_time</code>.
     */
    public Double getMinExecTime() {
        return this.minExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.min_exec_time</code>.
     */
    public PgStatStatementsPojo setMinExecTime(Double minExecTime) {
        this.minExecTime = minExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.max_exec_time</code>.
     */
    public Double getMaxExecTime() {
        return this.maxExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.max_exec_time</code>.
     */
    public PgStatStatementsPojo setMaxExecTime(Double maxExecTime) {
        this.maxExecTime = maxExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.mean_exec_time</code>.
     */
    public Double getMeanExecTime() {
        return this.meanExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.mean_exec_time</code>.
     */
    public PgStatStatementsPojo setMeanExecTime(Double meanExecTime) {
        this.meanExecTime = meanExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.stddev_exec_time</code>.
     */
    public Double getStddevExecTime() {
        return this.stddevExecTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.stddev_exec_time</code>.
     */
    public PgStatStatementsPojo setStddevExecTime(Double stddevExecTime) {
        this.stddevExecTime = stddevExecTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.rows</code>.
     */
    public Long getRows() {
        return this.rows;
    }

    /**
     * Setter for <code>public.pg_stat_statements.rows</code>.
     */
    public PgStatStatementsPojo setRows(Long rows) {
        this.rows = rows;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_hit</code>.
     */
    public Long getSharedBlksHit() {
        return this.sharedBlksHit;
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_hit</code>.
     */
    public PgStatStatementsPojo setSharedBlksHit(Long sharedBlksHit) {
        this.sharedBlksHit = sharedBlksHit;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_read</code>.
     */
    public Long getSharedBlksRead() {
        return this.sharedBlksRead;
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_read</code>.
     */
    public PgStatStatementsPojo setSharedBlksRead(Long sharedBlksRead) {
        this.sharedBlksRead = sharedBlksRead;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_dirtied</code>.
     */
    public Long getSharedBlksDirtied() {
        return this.sharedBlksDirtied;
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_dirtied</code>.
     */
    public PgStatStatementsPojo setSharedBlksDirtied(Long sharedBlksDirtied) {
        this.sharedBlksDirtied = sharedBlksDirtied;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.shared_blks_written</code>.
     */
    public Long getSharedBlksWritten() {
        return this.sharedBlksWritten;
    }

    /**
     * Setter for <code>public.pg_stat_statements.shared_blks_written</code>.
     */
    public PgStatStatementsPojo setSharedBlksWritten(Long sharedBlksWritten) {
        this.sharedBlksWritten = sharedBlksWritten;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_hit</code>.
     */
    public Long getLocalBlksHit() {
        return this.localBlksHit;
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_hit</code>.
     */
    public PgStatStatementsPojo setLocalBlksHit(Long localBlksHit) {
        this.localBlksHit = localBlksHit;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_read</code>.
     */
    public Long getLocalBlksRead() {
        return this.localBlksRead;
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_read</code>.
     */
    public PgStatStatementsPojo setLocalBlksRead(Long localBlksRead) {
        this.localBlksRead = localBlksRead;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_dirtied</code>.
     */
    public Long getLocalBlksDirtied() {
        return this.localBlksDirtied;
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_dirtied</code>.
     */
    public PgStatStatementsPojo setLocalBlksDirtied(Long localBlksDirtied) {
        this.localBlksDirtied = localBlksDirtied;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.local_blks_written</code>.
     */
    public Long getLocalBlksWritten() {
        return this.localBlksWritten;
    }

    /**
     * Setter for <code>public.pg_stat_statements.local_blks_written</code>.
     */
    public PgStatStatementsPojo setLocalBlksWritten(Long localBlksWritten) {
        this.localBlksWritten = localBlksWritten;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blks_read</code>.
     */
    public Long getTempBlksRead() {
        return this.tempBlksRead;
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blks_read</code>.
     */
    public PgStatStatementsPojo setTempBlksRead(Long tempBlksRead) {
        this.tempBlksRead = tempBlksRead;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.temp_blks_written</code>.
     */
    public Long getTempBlksWritten() {
        return this.tempBlksWritten;
    }

    /**
     * Setter for <code>public.pg_stat_statements.temp_blks_written</code>.
     */
    public PgStatStatementsPojo setTempBlksWritten(Long tempBlksWritten) {
        this.tempBlksWritten = tempBlksWritten;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.blk_read_time</code>.
     */
    public Double getBlkReadTime() {
        return this.blkReadTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.blk_read_time</code>.
     */
    public PgStatStatementsPojo setBlkReadTime(Double blkReadTime) {
        this.blkReadTime = blkReadTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.blk_write_time</code>.
     */
    public Double getBlkWriteTime() {
        return this.blkWriteTime;
    }

    /**
     * Setter for <code>public.pg_stat_statements.blk_write_time</code>.
     */
    public PgStatStatementsPojo setBlkWriteTime(Double blkWriteTime) {
        this.blkWriteTime = blkWriteTime;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_records</code>.
     */
    public Long getWalRecords() {
        return this.walRecords;
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_records</code>.
     */
    public PgStatStatementsPojo setWalRecords(Long walRecords) {
        this.walRecords = walRecords;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_fpi</code>.
     */
    public Long getWalFpi() {
        return this.walFpi;
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_fpi</code>.
     */
    public PgStatStatementsPojo setWalFpi(Long walFpi) {
        this.walFpi = walFpi;
        return this;
    }

    /**
     * Getter for <code>public.pg_stat_statements.wal_bytes</code>.
     */
    public BigDecimal getWalBytes() {
        return this.walBytes;
    }

    /**
     * Setter for <code>public.pg_stat_statements.wal_bytes</code>.
     */
    public PgStatStatementsPojo setWalBytes(BigDecimal walBytes) {
        this.walBytes = walBytes;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PgStatStatementsPojo (");

        sb.append(userid);
        sb.append(", ").append(dbid);
        sb.append(", ").append(queryid);
        sb.append(", ").append(query);
        sb.append(", ").append(plans);
        sb.append(", ").append(totalPlanTime);
        sb.append(", ").append(minPlanTime);
        sb.append(", ").append(maxPlanTime);
        sb.append(", ").append(meanPlanTime);
        sb.append(", ").append(stddevPlanTime);
        sb.append(", ").append(calls);
        sb.append(", ").append(totalExecTime);
        sb.append(", ").append(minExecTime);
        sb.append(", ").append(maxExecTime);
        sb.append(", ").append(meanExecTime);
        sb.append(", ").append(stddevExecTime);
        sb.append(", ").append(rows);
        sb.append(", ").append(sharedBlksHit);
        sb.append(", ").append(sharedBlksRead);
        sb.append(", ").append(sharedBlksDirtied);
        sb.append(", ").append(sharedBlksWritten);
        sb.append(", ").append(localBlksHit);
        sb.append(", ").append(localBlksRead);
        sb.append(", ").append(localBlksDirtied);
        sb.append(", ").append(localBlksWritten);
        sb.append(", ").append(tempBlksRead);
        sb.append(", ").append(tempBlksWritten);
        sb.append(", ").append(blkReadTime);
        sb.append(", ").append(blkWriteTime);
        sb.append(", ").append(walRecords);
        sb.append(", ").append(walFpi);
        sb.append(", ").append(walBytes);

        sb.append(")");
        return sb.toString();
    }
}
